### ISSUE TITLE
Runner Backend Proxy Api 

### ISSUE THREAD

**Issue by matthyy** [quentin-maison/sorare-helper#1]
Pour runner le backend:

1. unzip le fichier
2. cd nom du dossier
3. npm install pour installer les dépendances
4. node index.js pour lancer le serveur 
[
[sorare-helper-api.zip](https://github.com/quentin-maison/sorare-helper/files/7325096/sorare-helper-api.zip)
](url)

**Comment by quentin-maison** [comment]
Comme discuté je ne suis pas parvenu à le mettre en place. 
J'ai essayé de suivre les instructions: https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe

1) avec ta manip j'ai obtenu comme message "Example app listening at http://localhost:3001"
2) J'ai fait un fetch en prefixant mon URL avec celle du serveur:

http://localhost:3001/https://api.sorare.com/api/v1/users/m_quentin_m@hotmail.fr

Pour info j'ai placé le fetch dans 'sorare-helper/src/Fetch/Fetch.js'

**Comment by matthyy** [comment]
Re:
> avec ta manip j'ai obtenu comme message "Example app listening at http://localhost:3001 <http://localhost:3001/>"

Ca, c’es très bien. Ca veut dire que tu as serveur qui écoute sur le host localhost et sur le port 3001. Par exemple, si dans ton navigateur tu tapes l’url http://localhost:3001 <http://localhost:3001/>. Normalement, tu auras une réponse. 
Le but de ce serveur, c’est de faire proxy vers l’api de sorare. Ca veut dire que si tu appelles ***@***.*** ***@***.***>, en réalité tu appelleras ***@***.*** ***@***.***>. Peut importe l’url que tu rentreras, tu appelleras en fait sorare. 

Je ne sais pas si tu as regardé mais j’ai push du code dans l’app react ou je fais l’appel justement à l’api backend en faisant un fetch sur l’url : ***@***.*** ***@***.***>. Normalement, ça devrait marcher.

Dis moi si ça marche. Hope it helps.

**Comment by quentin-maison** [comment]
Ah ok, j'étais parti sur faire la manip du lien que je t'avais donné.
Alors quand j'entre le lien ca tourne dans le vide sur le browser (l'animation genre ca va s'actualiser mais ca le fait jamais) et rien n'apparait.
Sur le terminal ca donne ca : 

Example app listening at http://localhost:3001

(node:3928) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (C:\Users\Quentin\projets-dev\sorare-helper\sorare-helper-api\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Quentin\projets-dev\sorare-helper\sorare-helper-api\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Quentin\projets-dev\sorare-helper\sorare-helper-api\node_modules\axios\lib\adapters\http.js:293:11)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Si c'est plus simple pour toi on se fera un call quand tu as le temps ;)

**Comment by matthyy** [comment]
Même quand tu prends juste cette URL: ***@***.*** ***@***.***> et tu la copie colle dans ton navigateur, tu obtiens une erreur?
